// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHKthpNlzNpzoTCek8d7DfyK_YEx9eHbE',
    appId: '1:161407649420:web:cfb3d281cb0a779ee71da9',
    messagingSenderId: '161407649420',
    projectId: 'esports-9a85b',
    authDomain: 'esports-9a85b.firebaseapp.com',
    storageBucket: 'esports-9a85b.firebasestorage.app',
    measurementId: 'G-4984W899HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD44B62ACLwsChMJR61DQl80L56-vnlPWY',
    appId: '1:161407649420:android:f79822a957f4082ee71da9',
    messagingSenderId: '161407649420',
    projectId: 'esports-9a85b',
    storageBucket: 'esports-9a85b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoDcIaRZhIglolNsXzse4bFUjJL7G52Yo',
    appId: '1:161407649420:ios:40625be8c9ef78a4e71da9',
    messagingSenderId: '161407649420',
    projectId: 'esports-9a85b',
    storageBucket: 'esports-9a85b.firebasestorage.app',
    iosBundleId: 'com.STInnovations.esports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoDcIaRZhIglolNsXzse4bFUjJL7G52Yo',
    appId: '1:161407649420:ios:40625be8c9ef78a4e71da9',
    messagingSenderId: '161407649420',
    projectId: 'esports-9a85b',
    storageBucket: 'esports-9a85b.firebasestorage.app',
    iosBundleId: 'com.STInnovations.esports',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHKthpNlzNpzoTCek8d7DfyK_YEx9eHbE',
    appId: '1:161407649420:web:49b299669b7d5f07e71da9',
    messagingSenderId: '161407649420',
    projectId: 'esports-9a85b',
    authDomain: 'esports-9a85b.firebaseapp.com',
    storageBucket: 'esports-9a85b.firebasestorage.app',
    measurementId: 'G-SRW61K9DBN',
  );
}
